name: CI
on:
  push:
    # Git Push Event
    branches: [master]
  pull_request:
    branches: [master, develop]
    # branches: [main, dev, ...]
    paths:
      - '**.ts'
      - '**.tsx'
      - '!**/README.md'

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Use Node.js 12.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.x
      - name: yarn install, build
        run: |
          yarn install
          yarn build
      - name: run Lighthouse CI
        run: |
          yarn add global @lhci/cli
          lhci autorun
