name: SimplePipeline

on:
  push:
    # Git Push Event
    branches: [master]
    # branches: [main, dev, ...]

jobs:
  # 진행할 작업 명시
  lintTest:
    # 작업명
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo  "Running Installing Dependencies"
          yarn install
      - name: Run Linting
        run: |
          echo "Running Lining Tests"
          yarn lint
        env:
          CI: true
  securityCheck:
    # 작업명
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
        echo "Running Security Checks"
        sleep 5s;
        echo "Running Security Checks 1"
        sleep 5s;
        echo "Running Security Checks 2"
        sleep 5s;
        echo "Running Security Checks 3"
        sleep 5s;