name: SimplePipeline

on:
  push:
    # Git Push Event
    branches: [master]
  pull_request:
    branches: [master, develop]
    # branches: [main, dev, ...]
    paths:
      - '**.ts'
      - '**.tsx'
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  # 진행할 작업 명시
  lintTest:
    # 작업명
    name: Lint
    # action을 어떤 환경에서 실행시킬지 ( Require )
    runs-on: ubuntu-latest
    # Job 안에서 순차적으로 실행되는 프로세스 단위. step에서 명령을 내리거나, action을 실행할 수 있다.
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo  "Running Installing Dependencies"
          yarn install
      - name: Run Linting
        run: |
          echo "Running Lining Tests"
          yarn lint
      - name: Run Jest
        run: |
          echo  "Running Test Library"
          yarn test
        env:
          CI: true
  securityCheck:
    # 작업명
    name: Security Check
    # action을 어떤 환경에서 실행시킬지 ( Require )
    runs-on: ubuntu-latest
    # Job 안에서 순차적으로 실행되는 프로세스 단위. step에서 명령을 내리거나, action을 실행할 수 있다.
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks"
          sleep 5s;
          echo "Running Security Checks 1"
          sleep 5s;
          echo "Running Security Checks 2"
          sleep 5s;
          echo "Running Security Checks 3"
          sleep 5s;

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    # 배열안에 들어있는 job이 완료되면
    needs: [lintTest, securityCheck]
    steps:
      - name: Install Dependencies
        run: |
          echo  "Deployment"
          sleep 5s;
